name: kaljit
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  layout_simulator: ^0.1.2
  provider: ^6.0.5
  syncfusion_flutter_sliders: ^22.1.34
  syncfusion_flutter_core: ^22.1.34
  font_awesome_flutter: ^10.4.0
  flutter_draggable_gridview: ^0.0.8
  collection: ^1.17.1
  flutter_carousel_slider: ^1.1.0
  cloud_firestore:
  firebase_core:
  flutter_syntax_view:
  dart_style: ^2.3.1
  firebase_storage: ^11.2.3
  parallax_sensors_bg: ^1.0.1
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
